'use strict';
const assert = require('node:assert/strict');
const {UnifiedInfinityWallet, memoryStorage} = require('../unified-wallet');
(async () => {
  const storage=memoryStorage();
  const a=new UnifiedInfinityWallet({storage});a.createWallet({walletId:'player'});
  const b=new UnifiedInfinityWallet({storage});
  const reward=(id,kind='LEVEL_COMPLETED',walletId='player')=>({walletId,gameId:'SNAKES_REVENGE',rewardKind:kind,rewardId:id});
  const both=await Promise.all([a.creditStarCoinReward(reward('1')),b.creditStarCoinReward(reward('1'))]);
  assert.equal(both.filter(x=>x.credited).length,1);
  assert.equal(new UnifiedInfinityWallet({storage}).balance('player','STAR_COIN'),0.1);
  await Promise.all(Array.from({length:9},(_,i)=>b.creditStarCoinReward(reward('song'+i,'SONG_SHARED'))));
  assert.equal(b.balance('player','STAR_COIN'),1);
  assert.equal(await b.verifyChain(),true);
  await assert.rejects(b.creditStarCoinReward(reward('x','INVALID')));
  b.createWallet({walletId:'other'});
  await b.creditStarCoinReward(reward('1','LEVEL_COMPLETED','other'));
  assert.equal(b.balance('other','STAR_COIN'),0.1);
  assert.equal(b.balance('player','STAR_COIN'),1);
  const old=storage.getItem('infinity_unified_wallet_v1');
  const blocked={getItem:storage.getItem,setItem(){throw new Error('quota')}};
  const failed=new UnifiedInfinityWallet({storage:blocked});
  await assert.rejects(failed.creditStarCoinReward(reward('new')),/quota/);
  assert.equal(storage.getItem('infinity_unified_wallet_v1'),old);
  assert.equal(failed.balance('player','STAR_COIN'),1);
  const retry=await b.creditStarCoinReward(reward('new'));assert.equal(retry.credited,true);
  assert.equal(await b.verifyChain(),true);
  console.log('StarCoin reward tests passed: exact tenths, retries, concurrent duplicates, account isolation, atomic storage, hash chain.');
})().catch(e=>{console.error(e);process.exitCode=1});
